repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.12
  hooks:
    - id: ruff-check
      args: ["--config", "pyproject.toml"]
      language: system
    - id: ruff-format
      args: ["--config", "pyproject.toml"]
      language: system
